extends SceneTree
const Clock=preload("res://scripts/city_clock.gd")
const Daylight=preload("res://scripts/daylight_environment.gd")
class Fixture extends Node3D:
	var active:=true
	var paused:=false
	var environment:=WorldEnvironment.new()
	var sun:=Daylight.make_sun()
	func _init():
		environment.environment=Daylight.make_environment()
		add_child(environment)
		add_child(sun)
var checks:Array=[]
func check(name:String,passed:bool,evidence:Dictionary={}):
	checks.append({"name":name,"passed":passed,"evidence":evidence})
	print("CLOCK ","PASS " if passed else "FAIL ",name," ",JSON.stringify(evidence))
func _initialize():call_deferred("run")
func run():
	var game:=Fixture.new();root.add_child(game)
	var clock:=Clock.new();game.add_child(clock);clock.setup(game);clock.set_process(false)
	var base:Dictionary=clock.baseline
	check("default is 12x fixed summer at16",clock.hour==16 and clock.speed==12 and clock.running and base.samples==90)
	check("summer horizon spans approximately14 hours",absf(base.daylight_hours-13.95608)<.00001)
	for preset in ["sunrise","sunset"]:
		clock.jump(preset)
		var state:Dictionary=clock.solar_state()
		check(preset+" crosses apparent solar horizon",absf(state.elevation_deg+.833)<.00001,{"hour":clock.hour,"elevation_deg":state.elevation_deg})
		check(preset+" is in correct southeastern southwestern quarter",state.sun_direction.z>0 and (state.sun_direction.x>0 if preset=="sunrise" else state.sun_direction.x<0))
	clock.jump("noon")
	var noon:Dictionary=clock.solar_state()
	check("southern summer noon sun points north",noon.sun_direction.z<0 and absf(noon.sun_direction.x)<.00001 and noon.elevation_deg>70)
	clock.apply_state({});clock.advance(7200)
	check("real7200 seconds gives exactly one24hour cycle",is_equal_approx(clock.hour,16) and clock.cycles==1)
	clock.set_hour(0);clock.advance(300)
	check("real5 minutes advances game1 hour",is_equal_approx(clock.hour,1))
	clock.set_hour(23.99);clock.advance(6)
	check("midnight wraps without negative hours",absf(clock.hour-.01)<.00001 and clock.cycles==2 and clock.display_time()=="00:00")
	clock.set_hour(-1)
	check("seeking backward wraps to previous evening",clock.hour==23)
	clock.set_hour(49)
	check("seeking forward wraps to next day",clock.hour==1)
	clock.running=false;clock.advance(1000)
	check("photo freeze stops clock",clock.hour==1)
	clock.running=true;clock.set_speed(24);clock.advance(150)
	check("selected speed changes clock rate",clock.hour==2)
	clock.set_speed(1000);check("speed has bounded upper limit",clock.speed==120)
	clock.set_speed(0);check("freeze uses dedicated switch rather than zero rate",clock.speed==1)
	clock.set_speed(NAN);clock.set_hour(INF);clock.advance(-100);clock.advance(INF)
	check("invalid numeric inputs do not corrupt the clock",clock.hour==2 and clock.speed==1)
	game.paused=true;clock._process(60)
	check("game pause stops elapsed time",clock.hour==2)
	game.paused=false;game.active=false;clock._process(60)
	check("title screen does not consume a saved day",clock.hour==2)
	game.active=true;clock.set_speed(12);clock._process(60)
	check("active gameplay advances at configured speed",absf(clock.hour-2.2)<.000001)
	clock.set_hour(22)
	var updates:int=game.environment.environment.get_meta("cycle_sky_updates")
	game.paused=true;clock.set_hour(12)
	check("paused manual seek immediately updates actual sun and sky",game.sun.light_energy>0 and int(game.environment.environment.get_meta("cycle_sky_updates"))==updates+1)
	clock.set_hour(22)
	check("night removes below-horizon direct sun",game.sun.light_energy==0)
	clock.apply_state({"hour":19.7,"speed":24,"running":false,"cycles":17})
	var saved:Dictionary=JSON.parse_string(JSON.stringify(clock.get_state()))
	var restored:=Clock.new();game.add_child(restored);restored.setup(game);restored.set_process(false);restored.apply_state(saved)
	check("JSON save restore retains seek speed freeze and day count",restored.get_state()==clock.get_state())
	check("HUD clock reflects the saved time",restored.display_time()=="19:42")
	restored.apply_state({})
	check("legacy saves adopt summer defaults",restored.hour==16 and restored.speed==12 and restored.running and restored.cycles==0)
	restored.apply_state({"hour":NAN,"speed":INF,"cycles":-4})
	check("nonfinite save numbers fall back safely",restored.hour==16 and restored.speed==12 and restored.cycles==0)
	restored.apply_state({"hour":"dusk","speed":null,"running":"no","cycles":{}})
	check("malformed optional clock values retain safe legacy defaults",restored.hour==16 and restored.speed==12 and restored.running and restored.cycles==0)
	clock.set_hour(0);var previous:Dictionary=clock.solar_state(23.99999);var next:Dictionary=clock.solar_state(.00001)
	check("sun direction and twilight are continuous over midnight",previous.sun_direction.distance_to(next.sun_direction)<.00001 and absf(previous.night_factor-next.night_factor)<.00001)
	var old_flags:=[game.environment.environment.ssao_enabled,game.environment.environment.glow_enabled,game.environment.environment.ssr_enabled,game.sun.shadow_enabled]
	for hour in range(0,24):clock.set_hour(hour)
	check("24hours do not change expensive rendering feature flags",old_flags==[game.environment.environment.ssao_enabled,game.environment.environment.glow_enabled,game.environment.environment.ssr_enabled,game.sun.shadow_enabled])
	game.free()
	var passed:bool=checks.all(func(c):return c.passed)
	DirAccess.make_dir_recursive_absolute("res://../reports/city-clock")
	var report:={"passed":passed,"checks":checks,"source_hashes":{}}
	for path in ["res://scripts/city_clock.gd","res://assets/sydney_summer.json","res://../source/city_clock_test.gd"]:report.source_hashes[path]=FileAccess.get_sha256(path)
	FileAccess.open("res://../reports/city-clock/checks.json",FileAccess.WRITE).store_string(JSON.stringify(report,"\t"))
	print("CITY_CLOCK_COMPLETE ",checks.size()," passed=",passed)
	quit(0 if passed else 1)
